# Generated by Django 4.2.4 on 2023-08-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reviews', '0001_initial'),
        ('Towtrucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='towtruck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='Towtrucks.towtruck'),
        ),
    ]
