# Generated by Django 4.2.4 on 2023-08-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('production_year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[], max_length=20)),
                ('engine_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mileage', models.IntegerField()),
                ('has_damage', models.BooleanField(default=False)),
                ('accident_history', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('modifications', models.TextField(blank=True)),
                ('usage_purpose', models.TextField()),
                ('parking_situation', models.TextField()),
            ],
        ),
    ]
